/** Controlled templates assembled from Safety Blocks — add a form here, not a new page. */
import { assembleForm } from "../assemble";
import {
  CRANE_INSPECT_ITEMS,
  LUFFER_INSPECT_ITEMS,
  MONTHLY_MAINT_ITEMS,
  RIGGING_INSPECT_ITEMS,
  SELF_ERECT_INSPECT_ITEMS,
  SITE_INSPECT_ITEMS,
  TOWER_MONTHLY_ITEMS,
  TOWER_PREUSE_ITEMS,
  TOWER_WEEKLY_ITEMS,
  WEEKLY_MAINT_ITEMS,
  MANAGEMENT_REVIEW_ITEMS,
  OHS_MEETING_ITEMS,
  EMERGENCY_DRILL_ITEMS,
  YOUNG_NEW_WORKER_ITEMS,
  REFUSAL_ITEMS,
  PRE_ASSEMBLY_ITEMS,
  POWERLINE_30M33_ITEMS,
  RADIO_FREQ_ITEMS,
  NOP_TC_ITEMS,
  OPERATOR_ORIENT_ITEMS,
  TOWER_REPORT_ITEMS,
  SUPERVISOR_QUAL_ITEMS,
  CSA_COMPLIANCE_ITEMS,
  THARRP_COVER_ITEMS,
  NAVCAN_ITEMS,
  POWER_SOURCE_ITEMS,
  SITE_LAYOUT_ITEMS,
  TRAFFIC_PERMIT_ITEMS,
  NDT_ITEMS,
  HOIST_ROPE_ITEMS,
  OPERATOR_CERT_ITEMS,
  FLYTABLE_SJP_ITEMS,
  PLATFORM_SJP_ITEMS,
} from "../blocks";
import type { FormDef } from "../types";

export const FORM_TEMPLATES: FormDef[] = [
  assembleForm({
    id: "flha",
    title: "FIELD LEVEL HAZARD ASSESSMENT",
    number: "PROVEN-FRM-001",
    group: "Daily",
    description:
      "This shift, this lift, this ground. Not a signature collection.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "task" },
      { type: "crane" },
      { type: "hazard" },
      { type: "hazard" },
      { type: "control" },
      { type: "control" },
      { type: "ppe" },
      { type: "communication" },
      { type: "weather" },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "crane-pre-use",
    title: "CRANE PRE-USE INSPECTION",
    number: "PROVEN-FRM-002",
    group: "Daily",
    description: "This shift, this machine, this configuration. 14.35.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "crane" },
      { type: "inspection", inspectionItems: CRANE_INSPECT_ITEMS },
      { type: "weather" },
      { type: "powerlines" },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "rigging-inspection",
    title: "RIGGING INSPECTION",
    number: "PROVEN-FRM-003",
    group: "Daily",
    description: "Before the hitch takes load. Part 15.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "rigging" },
      { type: "inspection", inspectionItems: RIGGING_INSPECT_ITEMS },
      { type: "comments" },
      { type: "photo" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "crane-op-log",
    title: "CRANE OPERATOR LOG",
    number: "PROVEN-FRM-023",
    group: "Logs",
    description:
      "Hours, lifts, defects — dated and signed. Stays with the machine. 14.14.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "crane" },
      { type: "inspection", inspectionItems: CRANE_INSPECT_ITEMS },
      { type: "log" },
      { type: "weather" },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "rigger-log",
    title: "RIGGER LOG",
    number: "PROVEN-FRM-024",
    group: "Logs",
    description:
      "Gear used, lifts made, what was isolated. 15.31 before each shift.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "task" },
      { type: "load" },
      { type: "rigging" },
      { type: "inspection", inspectionItems: RIGGING_INSPECT_ITEMS },
      { type: "log" },
      { type: "photo" },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "jha",
    title: "JOB HAZARD ANALYSIS",
    number: "PROVEN-FRM-JHA",
    group: "Lifting",
    description:
      "Hazards, consequence, residual risk. The steps live in the SWP.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "task" },
      { type: "hazard" },
      { type: "hazard" },
      { type: "hazard" },
      { type: "control" },
      { type: "control" },
      { type: "control" },
      { type: "ppe" },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "lift-plan",
    title: "LIFT PLAN",
    number: "PROVEN-FRM-006",
    group: "Lifting",
    description: "Weight, COG, chart, path, people, abort — before the hook.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "task" },
      { type: "crane" },
      { type: "load" },
      { type: "rigging" },
      { type: "communication" },
      { type: "weather" },
      { type: "powerlines" },
      { type: "emergency" },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "critical-lift",
    title: "CRITICAL LIFT PLAN",
    number: "PROVEN-FRM-007",
    group: "Lifting",
    description: "Named supervision. Written plan. 14.42.1.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "task" },
      { type: "crane" },
      { type: "load" },
      { type: "rigging" },
      { type: "hazard" },
      { type: "hazard" },
      { type: "control" },
      { type: "control" },
      { type: "communication" },
      { type: "weather" },
      { type: "powerlines" },
      { type: "emergency" },
      { type: "comments" },
      { type: "signature" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "pre-lift-meeting",
    title: "PRE-LIFT MEETING",
    number: "PROVEN-FRM-009",
    group: "Lifting",
    description: "Everyone repeats the plan, the signals, who stops it.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "task" },
      { type: "load" },
      { type: "hazard" },
      { type: "control" },
      { type: "communication" },
      { type: "ppe" },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "site-inspection",
    title: "SITE INSPECTION",
    number: "PROVEN-FRM-020",
    group: "Inspection",
    description:
      "The lift area, the ground, the zone. Not the whole civil site. 3.5.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "crane" },
      { type: "inspection", inspectionItems: SITE_INSPECT_ITEMS },
      { type: "powerlines" },
      { type: "weather" },
      { type: "emergency" },
      { type: "hazard" },
      { type: "control" },
      { type: "corrective" },
      { type: "photo" },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "weekly-maintenance",
    title: "WEEKLY MAINTENANCE",
    number: "PROVEN-FRM-025",
    group: "Inspection",
    description:
      "Frequent inspection. Wire rope, leaks, pins, safety devices. 14.13.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "crane" },
      { type: "inspection", inspectionItems: WEEKLY_MAINT_ITEMS },
      { type: "log" },
      { type: "corrective" },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "monthly-maintenance",
    title: "MONTHLY MAINTENANCE",
    number: "PROVEN-FRM-026",
    group: "Inspection",
    description:
      "Periodic inspection. Structure, rope, brakes, LMI, certificates. 14.13.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "crane" },
      { type: "inspection", inspectionItems: MONTHLY_MAINT_ITEMS },
      { type: "log" },
      { type: "corrective" },
      { type: "photo" },
      { type: "comments" },
      { type: "signature" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "tower-pre-use",
    title: "TOWER PRE-USE INSPECTION",
    number: "PROVEN-FRM-027",
    group: "Inspection",
    description:
      "Topless / hammerhead. This shift, this configuration. Z248, 14.35.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "crane" },
      { type: "inspection", inspectionItems: TOWER_PREUSE_ITEMS },
      { type: "weather" },
      { type: "powerlines" },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "luffing-jib-inspection",
    title: "LUFFING JIB INSPECTION",
    number: "PROVEN-FRM-028",
    group: "Inspection",
    description: "MRH hydraulic or MR rope. Jib angle, luffing system, weathervane.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "crane" },
      { type: "inspection", inspectionItems: LUFFER_INSPECT_ITEMS },
      { type: "weather" },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "self-erect-inspection",
    title: "SELF-ERECT INSPECTION",
    number: "PROVEN-FRM-029",
    group: "Inspection",
    description: "Hup, Igo, Igo T. Unfold complete. Ballast locked. This jib position.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "crane" },
      { type: "inspection", inspectionItems: SELF_ERECT_INSPECT_ITEMS },
      { type: "weather" },
      { type: "powerlines" },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "tower-weekly-maintenance",
    title: "TOWER WEEKLY MAINTENANCE",
    number: "PROVEN-FRM-030",
    group: "Inspection",
    description:
      "Frequent inspection. Rope, leaks, limits, lubrication. 14.13.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "crane" },
      { type: "inspection", inspectionItems: TOWER_WEEKLY_ITEMS },
      { type: "log" },
      { type: "corrective" },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "tower-monthly-maintenance",
    title: "TOWER MONTHLY MAINTENANCE",
    number: "PROVEN-FRM-031",
    group: "Inspection",
    description:
      "Periodic inspection. Structure, full rope, slew, hydraulics. 14.13.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "crane" },
      { type: "inspection", inspectionItems: TOWER_MONTHLY_ITEMS },
      { type: "log" },
      { type: "corrective" },
      { type: "photo" },
      { type: "comments" },
      { type: "signature" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "equipment-defect",
    title: "EQUIPMENT DEFECT REPORT",
    number: "PROVEN-FRM-022",
    group: "Inspection",
    description: "Out of service is immediate. Not next Tuesday.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "crane" },
      { type: "inspection", inspectionItems: CRANE_INSPECT_ITEMS },
      { type: "corrective" },
      { type: "photo" },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "incident-report",
    title: "INCIDENT REPORT",
    number: "PROVEN-FRM-010",
    group: "Incident",
    description: "Facts. Do not hide the dent.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "task" },
      { type: "crane" },
      { type: "load" },
      { type: "incident" },
      { type: "photo" },
      { type: "emergency" },
      { type: "corrective" },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "near-miss",
    title: "NEAR-MISS REPORT",
    number: "PROVEN-FRM-011",
    group: "Incident",
    description: "Someone in the zone. A sling that started to cut.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "task" },
      { type: "hazard" },
      { type: "control" },
      { type: "comments" },
      { type: "photo" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "first-aid",
    title: "FIRST AID REPORT",
    number: "PROVEN-FRM-012",
    group: "Incident",
    description: "Site first aid and the employer. Regulator as the law requires.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "task" },
      { type: "emergency" },
      { type: "incident" },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "return-to-work",
    title: "RETURN-TO-WORK PLAN",
    number: "PROVEN-FRM-RTW",
    group: "Worker",
    description: "Restrictions named. Work matched. Not a paper promise.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "task" },
      { type: "corrective" },
      { type: "comments" },
      { type: "signature" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "management-review",
    title: "MANAGEMENT OHS REVIEW",
    number: "PROVEN-FRM-032",
    group: "Inspection",
    description: "3.3(d). Trends, actions, objectives. Not a lunch.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "inspection", inspectionItems: MANAGEMENT_REVIEW_ITEMS },
      { type: "corrective" },
      { type: "corrective" },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "ohs-meeting",
    title: "OHS MEETING",
    number: "PROVEN-FRM-033",
    group: "Daily",
    description: "Worker OHS meeting. Toolbox is the lift brief.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "inspection", inspectionItems: OHS_MEETING_ITEMS },
      { type: "corrective" },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "emergency-drill",
    title: "EMERGENCY DRILL",
    number: "PROVEN-FRM-034",
    group: "Incident",
    description: "Test the plan. Record what failed.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "emergency" },
      { type: "inspection", inspectionItems: EMERGENCY_DRILL_ITEMS },
      { type: "corrective" },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "refuse-unsafe-work",
    title: "REFUSAL OF UNSAFE WORK",
    number: "PROVEN-FRM-035",
    group: "Incident",
    description: "Work stays stopped until the danger is controlled.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "task" },
      { type: "hazard" },
      { type: "inspection", inspectionItems: REFUSAL_ITEMS },
      { type: "corrective" },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "orientation",
    title: "ORIENTATION",
    number: "PROVEN-FRM-015",
    group: "Worker",
    description: "Young or new worker topics in 3.23. Before they begin.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "inspection", inspectionItems: YOUNG_NEW_WORKER_ITEMS },
      { type: "ppe" },
      { type: "emergency" },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "pre-assembly-meeting",
    title: "PRE-ASSEMBLY MEETING",
    number: "PROVEN-FRM-036",
    group: "Binder",
    description: "Before the tower or self-erect goes up. Named people. Sequence. Abort.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "crane" },
      { type: "task" },
      { type: "inspection", inspectionItems: PRE_ASSEMBLY_ITEMS },
      { type: "communication" },
      { type: "weather" },
      { type: "emergency" },
      { type: "comments" },
      { type: "signature" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "powerline-30m33",
    title: "POWERLINE RECORD — 30M33",
    number: "PROVEN-FRM-037",
    group: "Binder",
    description:
      "Site schematic and the discussion. Coded 30M33 is the utility’s form.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "crane" },
      { type: "powerlines" },
      { type: "inspection", inspectionItems: POWERLINE_30M33_ITEMS },
      { type: "comments" },
      { type: "photo" },
      { type: "signature" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "radio-frequency",
    title: "RADIO FREQUENCY COORDINATION",
    number: "PROVEN-FRM-038",
    group: "Binder",
    description: "52E73C request plus the site radio log.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "crane" },
      { type: "communication" },
      { type: "inspection", inspectionItems: RADIO_FREQ_ITEMS },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "nop-tc-notice",
    title: "NOP-TC POSTING NOTICE",
    number: "PROVEN-FRM-039",
    group: "Binder",
    description: "What stays on the board. Submit the NOP online.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "crane" },
      { type: "inspection", inspectionItems: NOP_TC_ITEMS },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "operator-orientation",
    title: "OPERATOR CRANE ORIENTATION",
    number: "PROVEN-FRM-040",
    group: "Binder",
    description: "This machine. This site. This chart.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "crane" },
      { type: "inspection", inspectionItems: OPERATOR_ORIENT_ITEMS },
      { type: "communication" },
      { type: "powerlines" },
      { type: "emergency" },
      { type: "comments" },
      { type: "signature" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "tower-crane-report",
    title: "TOWER CRANE REPORT",
    number: "PROVEN-FRM-041",
    group: "Binder",
    description: "After erect, climb or reposition. Companion to WorkSafeBC’s checklist.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "crane" },
      { type: "inspection", inspectionItems: TOWER_REPORT_ITEMS },
      { type: "corrective" },
      { type: "photo" },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "supervisor-qualification",
    title: "ACTIVITY SUPERVISOR QUALIFICATION",
    number: "PROVEN-FRM-042",
    group: "Binder",
    description: "14.73.2. This particular crane. This activity.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "crane" },
      { type: "inspection", inspectionItems: SUPERVISOR_QUAL_ITEMS },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "csa-compliance",
    title: "CSA Z248 COMPLIANCE RECORD",
    number: "PROVEN-FRM-043",
    group: "Binder",
    description: "14.2(6). How this serial meets Z248-2004.",
    blocks: [
      { type: "project" },
      { type: "crane" },
      { type: "inspection", inspectionItems: CSA_COMPLIANCE_ITEMS },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "tharrp-cover",
    title: "THARRP / HIGH-ANGLE RESCUE COVER",
    number: "PROVEN-FRM-044",
    group: "Binder",
    description: "Who requested the survey. Which fire department. How to summon them.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "crane" },
      { type: "emergency" },
      { type: "inspection", inspectionItems: THARRP_COVER_ITEMS },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "navcan-land-use",
    title: "NAV CANADA / AERONAUTICAL FILE",
    number: "PROVEN-FRM-045",
    group: "Binder",
    description: "Land-use and obstacle file. Portal submissions, not a Proven permit.",
    blocks: [
      { type: "project" },
      { type: "crane" },
      { type: "inspection", inspectionItems: NAVCAN_ITEMS },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "power-source",
    title: "POWER SOURCE RECORD",
    number: "PROVEN-FRM-046",
    group: "Binder",
    description: "How the crane is fed. Who can isolate it.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "crane" },
      { type: "inspection", inspectionItems: POWER_SOURCE_ITEMS },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "site-layout",
    title: "SITE LAYOUT COVER",
    number: "PROVEN-FRM-047",
    group: "Binder",
    description: "Cover sheet for the drawing package.",
    blocks: [
      { type: "project" },
      { type: "crane" },
      { type: "inspection", inspectionItems: SITE_LAYOUT_ITEMS },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "traffic-permits",
    title: "TRAFFIC AND STREET-USE PERMITS",
    number: "PROVEN-FRM-048",
    group: "Binder",
    description: "Cover sheet for municipal permits.",
    blocks: [
      { type: "project" },
      { type: "inspection", inspectionItems: TRAFFIC_PERMIT_ITEMS },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "ndt-record",
    title: "NDT RECORD",
    number: "PROVEN-FRM-049",
    group: "Binder",
    description: "Cover sheet for the current NDT report on this serial.",
    blocks: [
      { type: "project" },
      { type: "crane" },
      { type: "inspection", inspectionItems: NDT_ITEMS },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "hoist-rope-record",
    title: "HOIST ROPE RECORD",
    number: "PROVEN-FRM-050",
    group: "Binder",
    description: "The rope on the drum. Mill cert. Date on. Condition.",
    blocks: [
      { type: "project" },
      { type: "crane" },
      { type: "inspection", inspectionItems: HOIST_ROPE_ITEMS },
      { type: "log" },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "operator-certification",
    title: "OPERATOR CERTIFICATION FILE",
    number: "PROVEN-FRM-051",
    group: "Binder",
    description: "BC Crane Safety ticket. Provisional plan if required.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "crane" },
      { type: "inspection", inspectionItems: OPERATOR_CERT_ITEMS },
      { type: "comments" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "flytable-cycle-sjp",
    title: "FLYTABLE CYCLE SJP",
    number: "PROVEN-FRM-052",
    group: "Lifting",
    description:
      "This table. This floor. This drawing. Critical lift. Mark nontypical if it is.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "task" },
      { type: "crane" },
      { type: "load" },
      { type: "rigging" },
      { type: "communication" },
      { type: "weather" },
      { type: "inspection", inspectionItems: FLYTABLE_SJP_ITEMS },
      { type: "hazard" },
      { type: "control" },
      { type: "emergency" },
      { type: "comments" },
      { type: "signature" },
      { type: "signature" },
    ],
  }),
  assembleForm({
    id: "loading-platform-sjp",
    title: "LOADING PLATFORM SJP",
    number: "PROVEN-FRM-053",
    group: "Lifting",
    description:
      "This deck. This floor. This serial. Empty. Critical lift.",
    blocks: [
      { type: "worker" },
      { type: "project" },
      { type: "task" },
      { type: "crane" },
      { type: "load" },
      { type: "rigging" },
      { type: "communication" },
      { type: "weather" },
      { type: "inspection", inspectionItems: PLATFORM_SJP_ITEMS },
      { type: "hazard" },
      { type: "control" },
      { type: "emergency" },
      { type: "comments" },
      { type: "signature" },
      { type: "signature" },
    ],
  }),
];

export function getTemplate(id: string) {
  return FORM_TEMPLATES.find((f) => f.id === id);
}
